title: 'SUZUKI VITARA # AUTOPADOVA'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3479079569224268
  brandStrength: 0.2491681061219424
  rhythmicContrast: 0.2096064072102308
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  lightness: 0.0923956788610667
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Suzuki Vitara
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3577694
layout_spectrum: 0.9786968
