name: Suzuki Vitara
favicon: null
layout_spectrum: 0.19967571482993662
typography_spectrum: 0.6373457240406424
title: 'SUZUKI VITARA # AUTOPADOVA'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2491681061219424
  lightness: 0.0923956788610667
  saturation: 0.3479079569224268
  rhythmicContrast: 0.20960640721023083
purpose: []
