name: Suzuki Vitara
favicon: null
layout_spectrum: 0.9786968
typography_spectrum: 0.3577694
title: 'SUZUKI VITARA # AUTOPADOVA'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#792388'
    - '#e7c3ed'
    - '#297e1b'
    - '#6ca264'
  brandStrength: 0.2491681061219424
  lightness: 0.0923956788610667
  saturation: 0.3479079569224268
  rhythmicContrast: 0.2096064072102308
purpose: []
