typography_spectrum: 0.3577694
color:
  brandColors:
    - '#ffffff'
    - '#792388'
    - '#e7c3ed'
    - '#297e1b'
    - '#6ca264'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.3479079569224268
  rhythmicContrast: 0.2096064072102308
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9786968
analytics:
  google: null
  facebook: null
  twitter: null
name: Suzuki Vitara
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Suzuki Dealer
    url: 'http://www.suzuki-bacau.ro/autoturisme/suzuki/'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'SUZUKI # AUTOPADOVA'
purpose: []
